[tox]
envlist = flake8, pydocstyle, py310, py311, py312, py313


[gh-actions]
python =
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313


[testenv]
commands =
    python -m pytest --doctest-modules scholia
    python -m pytest tests
deps=
    pytest
    -rrequirements.txt


[testenv:flake8]
commands = flake8 scholia
deps =
    flake8
    flake8-docstrings

[testenv:pydocstyle]
commands = pydocstyle --convention=numpy scholia
deps =
    pydocstyle

[testenv:docs]
description = Build Sphinx documentation
deps =
    -rrequirements.txt
    -rdocs/requirements.txt
commands =
    sphinx-build -b html docs docs/_build/html
