{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?mol ?molLabel ?InChIKey ?CAS ?ChemSpider ?PubChem_CID {
  ?mol wdt:P235 ?InChIKey .
  FILTER (REGEX(?InChIKey,"^_shortkey_"))
  OPTIONAL {
    ?mol wdt:P231 ?CAS
  }
  OPTIONAL {
    ?mol wdt:P661 ?ChemSpider
  }
  OPTIONAL {
    ?mol wdt:P662 ?PubChem_CID
  }
  {{ sparql_helpers.labels(["?mol"], languages) }}
}
