#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

# Author's most cited works
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT ?count ?work (REPLACE(STR(?work), ".*/", "") AS ?workLabel) 

WHERE {
  { SELECT (count(?citing_work) as ?count) ?work WHERE {
    ?work wdt:P50 target: .
    OPTIONAL { ?citing_work wdt:P2860 ?work . }
  }
  GROUP BY ?work }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . }        
}  
ORDER BY DESC(?count)
LIMIT 500
