{% import 'sparql-helpers.sparql' as sparql_helpers -%}
#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
# Author's most cited works
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?count ?work ?workLabel WHERE {
  {
    SELECT (COUNT(?citing_work) AS ?count) ?work WHERE {
      ?work wdt:P50 target: .
      OPTIONAL {
        ?citing_work wdt:P2860 ?work .
      }
    }
    GROUP BY ?work
  }
  {{ sparql_helpers.labels(["?work"], languages) }}
}
ORDER BY DESC(?count)
LIMIT 500
