SELECT
  # Number of works with the coauthor
  ?count

  # The citing author as a string, - rather than as an item
  ?citing_author

  # Build URL to the Author disambiguator tool
  (CONCAT(
      'https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=',
      ENCODE_FOR_URI(?citing_author)) AS ?resolver_url)

  ?example_citing_work ?example_citing_workLabel
WITH {
  SELECT
    (COUNT(?work) as ?count)
    ?citing_author
    (SAMPLE(?citing_work) AS ?example_citing_work) 
  WHERE {
    ?work wdt:P50 wd:{{ q }} .
    ?citing_work wdt:P2860 ?work .
    ?citing_work wdt:P2093 ?citing_author .
  }
  GROUP BY ?citing_author
} AS %result
WHERE {
  INCLUDE %result
  # Label the results
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,nl,no,ru,sv,zh". }
}
ORDER BY DESC(?count)
LIMIT 1000