{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?work ?workLabel ?topic ?topicLabel WHERE {
  ?work wdt:P50 target: .
  ?work wdt:P921 ?topic .
  OPTIONAL {
    ?work wdt:P577 ?publication_date
  }
  {{ sparql_helpers.labels(["?work", "?topic"], languages) }}
}
ORDER BY ?publication_date
