#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?theme (REPLACE(STR(?theme), ".*/", "") AS ?themeLabel) ?example_work (REPLACE(STR(?example_work), ".*/", "") AS ?example_workLabel) WHERE {
  {
    SELECT (COUNT(?work) AS ?count) ?theme (SAMPLE(?work) AS ?example_work) WHERE {
      ?work wdt:P50 target: .
      ?work wdt:P921 ?theme .
    }
    GROUP BY ?theme
  }
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . } 
}
ORDER BY DESC(?count)
