#defaultView:Map
SELECT DISTINCT ?image ?item ?itemLabel ?geo (?property_item_label AS ?layer)
WHERE {
  wd:{{ q }} ?property ?item . 
  ?item p:P159/pq:P625 | wdt:P276*/wdt:P625 ?geo .
  ?property_item wikibase:directClaim ?property .
  OPTIONAL { ?item wdt:P18 ?image . } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,nl,no,ru,sv,zh". }
  
  # No automatic labeling on the property, - for some reason.
  ?property_item rdfs:label ?property_item_label . FILTER(LANG(?property_item_label) = 'en')
}
