#defaultView:BarChart
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?year (COUNT(DISTINCT ?citing_work) AS ?count) ?kind WHERE {
  ?work wdt:P50 target: .
  ?citing_work wdt:P2860 ?work .
  BIND (IF(EXISTS {
    ?citing_work wdt:P50 target:
  },"self-citations","citations from others") AS ?kind)
  ?citing_work wdt:P577 ?date .
  BIND (STR(YEAR(?date)) AS ?year)
}
GROUP BY ?year ?kind
ORDER BY DESC(?year)
