{% import 'sparql-helpers.sparql' as sparql_helpers -%}
#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?theme ?themeLabel ?example_work ?example_workLabel WHERE {
  {
    SELECT (COUNT(?work) AS ?count) ?theme (SAMPLE(?work) AS ?example_work) WHERE {
      ?work wdt:P50 target: .
      ?work wdt:P921 ?theme .
    }
    GROUP BY ?theme
  }
  {{ sparql_helpers.labels(["?theme", "?example_work"], languages) }}
}
ORDER BY DESC(?count)
