PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT
  ?number_of_corecipients
  ?award ?awardLabel ?awardDescription
WITH {
     SELECT DISTINCT ?award (COUNT(?recipient) AS ?number_of_corecipients) WHERE {
    ?recipient wdt:P166 target: .
	?recipient wdt:P166 ?award .
			       FILTER (?award != target:)
     }
     GROUP BY ?award
} AS %result
WHERE {
  INCLUDE %result 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,da,de,es,fr,jp,no,ru,sv,zh" . }  
}
ORDER BY DESC(?number_of_corecipients)
