#defaultView:BubbleChart
# Count the number of time works by award recipients have set a main topic
SELECT ?count ?topic ?topicLabel 
WITH {
  SELECT ?topic (COUNT(?work) AS ?count) WHERE {
    ?recipient wdt:P166 wd:{{ q }} .
    ?work wdt:P50 ?recipient .
    ?work wdt:P921 ?topic .
  }
  GROUP BY ?topic
} AS %result
WHERE {
  INCLUDE %result 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,no,ru,sv,zh" . }  
}
ORDER BY DESC(?count)
LIMIT 50