{% import 'sparql-helpers.sparql' as sparql_helpers -%}
#defaultView:ImageGrid
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?image ?item ?itemLabel WHERE {
  ?item wdt:P972 target: ;
        wdt:P18 ?image .
  {{ sparql_helpers.labels(["?item"], languages) }}
}
