{% import 'sparql-helpers.sparql' as sparql_helpers -%}
# title: identifiers for this chemical class
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?IDpred ?IDpredLabel ?id ?idUrl ?IDpredDescription {
  target: ?IDdir ?id .
  ?IDpred wikibase:directClaim ?IDdir ;
          wdt:P31 wd:Q19833835 .
  OPTIONAL {
    ?IDpred wdt:P1630 ?formatterurl .
  }
  BIND (IRI(REPLACE(?formatterurl, '\\\\$1', STR(?id))) AS ?idUrl) .
  {{ sparql_helpers.labels(["?IDpred"], languages) }}
  {{ sparql_helpers.descriptions(["?IDpred"], languages) }}
}
ORDER BY ASC(?IDpredLabel)
LIMIT 500
