PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT DISTINCT ?matrix ?matrixLabel ?taxon ?taxonLabel (CONCAT("/taxon/", SUBSTR(STR(?taxon), 32)) AS ?taxonUrl) WHERE {
  VALUES ?chemical { target: }
  ?chemical wdt:P361 ?matrix.
  ?matrix (wdt:P279*/wdt:P1582) ?taxon .
  ?matrix wdt:P527 ?chemical.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
} ORDER BY ASC(?taxonLabel)
  LIMIT 250
