{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?wikis ?compound ?compoundLabel ?formula WHERE {
  {
    SELECT ?wikis ?compound WHERE {
      ?compound wdt:P31 wd:Q113145171 ;
                wikibase:sitelinks ?wikis . # hint:Prior hint:rangeSafe true .
      FILTER (?wikis >= 40)
      FILTER (NOT EXISTS {
          ?compound wdt:P2117 []
        })
    }
    ORDER BY DESC(?wikis)
    LIMIT 100
  }
  OPTIONAL {
    ?compound wdt:P274 ?formula
  }
  {{ sparql_helpers.labels(["?compound"], languages) }}
}
ORDER BY DESC(?wikis)
