{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
# title: structural identifiers for this chemical structure
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?Structural_identifier ?Structural_identifierLabel ?idLit (SAMPLE(?idUrls) AS ?idUrl) {
  {
    SELECT ?Structural_identifier ?idLit ?formatterurl WHERE {
      VALUES ?Structural_identifier { wd:P233 wd:P234 wd:P2017 }
      target: ?IDdir ?idLit .
      ?Structural_identifier wikibase:directClaim ?IDdir ;
                             wdt:P31 wd:Q19833835 .
      OPTIONAL {
        ?Structural_identifier wdt:P1630 ?formatterurl .
      }
    }
    LIMIT 500
  }
  BIND (IRI(REPLACE(?formatterurl, '\\\\$1', STR(?idLit))) AS ?idUrls) .
  {{ sparql_helpers.labels(["?Structural_identifier"], languages) }}
}
GROUP BY ?Structural_identifier ?Structural_identifierLabel ?idLit
ORDER BY ASC(?ID_TypeLabel)
