SELECT
  ?IDpred ?IDpredLabel
  ?id ?idUrl
  ?IDpredDescription
{
  wd:{{ q }} ?IDdir ?id .
  ?IDpred wikibase:directClaim ?IDdir ;
            wdt:P31 wd:Q19833835 .
  OPTIONAL {
    ?IDpred wdt:P1630 ?formatterurl .
  }
  BIND(IRI(REPLACE(?formatterurl, '\\\\$1', str(?id))) AS ?idUrl).
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,nl,no,ru,sv,zh" . }
}
ORDER BY ASC(?IDpredLabel)
LIMIT 500
