# title: biological processes in which this chemical is involved
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT DISTINCT
  ?pathway ?pathwayLabel
  (CONCAT("/pathway/", SUBSTR(STR(?pathway), 32)) AS ?pathwayUrl)
  ?pathwayDescription
WHERE {
  ?pathway wdt:P527 target: ;
           wdt:P31 / wdt:P279* wd:Q2996394 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}
ORDER BY ASC(?pathwayLabel)
LIMIT 250
