PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT (COUNT(?citingArticle) AS ?count) 
?citedArticle ?citedArticleLabel (CONCAT("/work/", SUBSTR(STR(?citedArticle), 32)) AS ?citedArticleUrl) WHERE {
  VALUES ?INTENTION { target: }
  ?citingArticle p:P2860 ?citationStatement .
  ?citationStatement ps:P2860 ?citedArticle ;
                     pq:P3712 ?INTENTION .
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
} GROUP BY ?citedArticle ?citedArticleLabel
  ORDER BY DESC(?count)
