#defaultView:BarChart
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?year (COUNT(?work) AS ?number_of_publications) ?role WHERE {
  {
    SELECT ?work (MIN(?years) AS ?year) ?type_ ?venue WHERE {
      ?work wdt:P577 ?dates ;
            p:P2860 ?citesStatement .
      ?citesStatement pq:P3712/wdt:P31 wd:Q96471816 .
      BIND (STR(YEAR(?dates)) AS ?years) .
      OPTIONAL {
        ?work wdt:P31 wd:Q109229154 .
        BIND ("explicit" AS ?type_)
        ?work wdt:P1433 ?venue_ .
        ?venue_ rdfs:label ?venue . FILTER (LANG(?venue) = "en")
        MINUS {
          ?venue_ wdt:P31 wd:Q1143604
        }
      }
      OPTIONAL {
        BIND ("nanopub" AS ?type_)
        BIND ("Nanopublication" AS ?venue)
        ?citesStatement prov:wasDerivedFrom ?reference .
        ?reference pr:P854 | pr:P12545 ?referenceURL .
        FILTER (STRSTARTS(STR(?referenceURL),"https://w3id.org/np/") || STRSTARTS(STR(?referenceURL),"http://purl.org/np/"))
      }
    }
    GROUP BY ?work ?type_ ?venue
  }
  BIND (COALESCE(IF(BOUND(?type_),?venue,'other source')) AS ?role)
}
GROUP BY ?year ?role
ORDER BY ?year
