SELECT ?journal ?journalLabel (COUNT(DISTINCT ?citationStatement) AS ?citations) (COUNT(DISTINCT ?citingArticle) AS ?articles) WHERE {
  ?citingArticle p:P2860 ?citationStatement ;
                 wdt:P1433 ?journal .
  ?citationStatement pq:P3712 ?intention ;
                     ps:P2860 ?citedArticle .
  ?intention wdt:P31 wd:Q96471816 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} GROUP BY ?journal ?journalLabel
  ORDER BY DESC(?citations)
