PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?date ?work ?workLabel ?venue ?venueLabel WHERE {
  {
    SELECT DISTINCT ?date ?work (SAMPLE(?venue_) AS ?venue) WHERE {
      ?work wdt:P577 ?dates ;
            p:P2860/pq:P3712/wdt:P31 wd:Q96471816 .
      BIND (xsd:date(?dates) AS ?date)
      ?work wdt:P31 wd:Q109229154 .
      BIND ("explicit" AS ?type_)
      ?work wdt:P1433 ?venue_ .
    }
    GROUP BY ?date ?work
  }
  ?work rdfs:label ?workLabel . FILTER(LANG(?workLabel) = 'en' || LANG(?workLabel) = 'mul')
  ?venue rdfs:label ?venueLabel . FILTER(LANG(?venueLabel) = 'en' || LANG(?venueLabel) = 'mul')
}
ORDER BY DESC(?date)
LIMIT 50
