# title: Clinical trials sorted according to date
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?start_date ?trial (REPLACE(STR(?trial), ".*/", "") AS ?trialLabel) WHERE {
  {
    SELECT * WHERE {
      ?trial wdt:P31 wd:Q30612 .
      ?trial wdt:P580 ?start_datetime .
      # hint:Prior hint:rangeSafe true .
    }
    ORDER BY DESC(?start_datetime)
    LIMIT 500
  }
  BIND (xsd:date(?start_datetime) AS ?start_date)
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en,da,de,es,fr,jp,nl,no,ru,sv,zh". }
}
ORDER BY DESC(?start_datetime)
