SELECT ?start_date ?trial ?trialLabel WHERE {
  {
    SELECT * WHERE { 
      ?trial wdt:P31 wd:Q30612 .
      OPTIONAL {
        ?trial wdt:P580 ?start_datetime .
        BIND(xsd:date(?start_datetime) AS ?start_date) 
      }
    }
    ORDER BY DESC(?start_datetime)
    LIMIT 500
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,nl,no,ru,sv,zh". }
}
ORDER BY DESC(?start_datetime)