PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?country ?countryLabel ?countryDescription ?example_work ?example_workLabel WHERE {
  {
    SELECT ?country WHERE {
      #    VALUES ?country { {% for q in qs %} wd:{{ q }} {% endfor %} }
    }
    GROUP BY ?country
  }
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . }
}
