{% import 'sparql-helpers.sparql' as sparql_helpers -%}
# title: Locations as topics for a specific country
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
#defaultView:Map{"markercluster":true}.
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?location ?locationLabel ?work ?workLabel ?geo ?layer WHERE {
  {
    SELECT ?location ?work ?geo ?type WHERE {
      ?location wdt:P17 target: .
      # Geocoordinates may possible be under a headquarter property
      ?location wdt:P159?/wdt:P625 ?geo .
      ?work wdt:P921 ?location .
      # Filter encyclopedic articles - that may not be so relevant
      FILTER NOT EXISTS {
        ?work wdt:P31 wd:Q17329259
      }
    }
  }
  # Move here for speed of query
  OPTIONAL {
    ?work wdt:P31/rdfs:label ?layer .
    FILTER (LANG(?layer) = 'en')
  }
  {{ sparql_helpers.labels(["?location", "?work"], languages) }}
}
