PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT ?sponsor ?sponsorLabel ?sponsorUrl ?sponsorDescription
WHERE {
  target: wdt:P859 ?sponsor .
  BIND(CONCAT("/sponsor/", SUBSTR(STR(?sponsor), 32)) AS ?sponsorUrl)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
