{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?description ?descriptionLabel ?descriptionUrl ?value ?valueLabel ?valueUrl WHERE {
  {
    BIND (1 AS ?order)
    BIND ("Event series" AS ?description)
    BIND ("/event-series" AS ?descriptionUrl)
    target: wdt:P179 ?value .
    BIND (CONCAT("/event-series/", SUBSTR(STR(?value),32)) AS ?valueUrl)
  }
  UNION {
    BIND (2 AS ?order)
    BIND ("Short name" AS ?description)
    target: wdt:P1813 ?value .
  }
  UNION {
    BIND (5 AS ?order)
    BIND (wd:Q34770 AS ?description)
    BIND ("/language" AS ?descriptionUrl)
    target: wdt:P2936 ?value .
    BIND (CONCAT("/language/", SUBSTR(STR(?value),32)) AS ?valueUrl)
  }
  UNION {
    SELECT (10 AS ?order) ("Organizers" AS ?description) (GROUP_CONCAT(?value_; SEPARATOR=", ") AS ?value) (CONCAT("/authors/", GROUP_CONCAT(?q; SEPARATOR=",")) AS ?valueUrl) {
      BIND (1 AS ?dummy)
      target: wdt:P664 ?iri .
      BIND (SUBSTR(STR(?iri),32) AS ?q)
      ?iri rdfs:label ?value_string .
      FILTER (LANG(?value_string) = 'en')
      BIND (COALESCE(?value_string, ?q) AS ?value_)
    }
    GROUP BY ?dummy
  }
  UNION {
    BIND (20 AS ?order)
    BIND ("Number of participants" AS ?description)
    target: wdt:P1132 ?value .
  }
  UNION {
    # number of submissions
    BIND (21 AS ?order)
    BIND ("number of submissions" AS ?description)
    target: p:P12655 ?value_statement .
    ?value_statement ps:P12655 ?submissions .
    OPTIONAL {
      ?value_statement pq:P518/rdfs:label ?track .
      FILTER (LANG(?track) = "en")
    }
    BIND (IF(BOUND(?track),CONCAT(STR(?submissions), " (", ?track, ")"),STR(?submissions)) AS ?value)
  }
  UNION {
    # number of accepted contributions
    BIND (22 AS ?order)
    BIND ("number of accepted contributions" AS ?description)
    target: p:P12649 ?value_statement .
    ?value_statement ps:P12649 ?accepted .
    OPTIONAL {
      ?value_statement pq:P518/rdfs:label ?track .
      FILTER (LANG(?track) = "en")
    }
    BIND (IF(BOUND(?track),CONCAT(STR(?accepted), " (", ?track, ")"),STR(?accepted)) AS ?value)
  }
  UNION {
    BIND (23 AS ?order)
    BIND ("Acceptance&nbsp;rate" AS ?description)
    target: p:P5822 ?value_statement .
    ?value_statement ps:P5822 ?acceptance_rate .
    OPTIONAL {
      ?value_statement pq:P518/rdfs:label ?track .
      FILTER (LANG(?track) = "en")
    }
    BIND (IF(BOUND(?track),CONCAT(STR(?acceptance_rate * 100), " % (", ?track, ")"),CONCAT(STR(?acceptance_rate * 100), " %")) AS ?value)
  }
  {{ sparql_helpers.labels(["?description", "?value"], languages) }}
}
ORDER BY ?order
