#defaultView:Timeline

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT ?time ?item ?itemLabel ?image
WHERE {
  {
    target: wdt:P580 | wdt:P585 ?time .
    OPTIONAL { target: wdt:P18 ?image . }
    BIND(wd:Q24575110 AS ?item)
  }
  UNION
  {
    target: wdt:P582 ?time .
    OPTIONAL { target: wdt:P18 ?image . }
    BIND(wd:Q24575125 AS ?item)
  }
  UNION 
  { target: p:P793 [ ps:P793 ?item ; pq:P585 ?time ] . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

