PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT
  ?protein ?proteinLabel ?proteinDescription
WITH {
  SELECT ?protein
  WHERE {
    target: wdt:P31 wd:Q7187 ;
      wdt:P688 ?protein .
  }
} AS %result 
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}