SELECT ?count ?description
WHERE {
{ {SELECT (COUNT(*) AS ?c) WHERE {?s ?p ?o} } BIND("Total number of triples" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {?s rdf:type wikibase:BestRank } } BIND("Total number of statements" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {?p a wikibase:Property} } BIND("Total number of properties" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P50 []} } BIND("Links from works to authors" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P69 []} } BIND("Links from people to where they were educated" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P108 []} } BIND("Links from people to employers" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P166 []} } BIND("Links from people to awards" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P212 []} } BIND("ISBN 13 book numbers" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P225 []} } BIND("Taxon names" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P234 []} } BIND("InChIs" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P236 []} } BIND("ISSNs" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P496 []} } BIND("ORCIDs" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P625 []} } BIND("Geolocations" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P638 []} } BIND("Protein Data Bank IDs" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P686 []} } BIND("Gene Ontology IDs" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P698 []} } BIND("PubMed ID" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P818 []} } BIND("arXiv IDs" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P859 []} } BIND("Links to sponsors" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P921 []} } BIND("Links from works to their main subjects" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P932 []} } BIND("Items with a PubMed Central ID" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P356 []} } BIND("Items with a DOI" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P1416 []} } BIND("Links from people to their affiliations" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P2093 []} } BIND("Author name strings" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P2427 []} } BIND("Items with a GRID ID" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P2860 []} } BIND("Citations" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P31 wd:Q13442814.} } BIND("Scholarly articles" AS ?d)} UNION
{ {SELECT (COUNT(*) AS ?c) WHERE {[] wdt:P31 []} } BIND("Things in Wikidata" AS ?d)} UNION
{ {SELECT (COUNT(DISTINCT ?work) AS ?c) WHERE { { ?work wdt:P31 wd:Q45182324 . } UNION { ?work wdt:P793 wd:Q7316896 . } UNION { ?work wdt:P5824 [] . } } } BIND("Retracted articles" AS ?d)}
BIND (?c AS ?count)
BIND (?d AS ?description)
}
ORDER BY DESC(?c)
