PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT
  ?publication_date
  ?work ?workLabel ?workDescription (CONCAT("/work/", SUBSTR(STR(?work), 32)) AS ?workUrl)
WITH {
  SELECT
    ?publication_date_
    ?work
  WHERE {
    VALUES ?publication_date_ {
      {% for day in range(-32, 1) %} {{ '"{}T00:00:00Z"^^xsd:dateTime'.format((datetime.datetime.now().date() + datetime.timedelta(day)).isoformat()) }} {% endfor %} 
    }
    ?work wdt:P407 target: ;
          wdt:P577 ?publication_date_ ;
  }
  LIMIT 1000
} AS %works_sample
WITH {
  SELECT
    (xsd:date(MAX(?publication_date_)) AS ?publication_date)
    ?work
  WHERE {
    INCLUDE %works_sample
  }
  GROUP BY ?work
  ORDER BY DESC(?publication_date)
  LIMIT 500
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}
ORDER BY DESC(?publication_date)

  