PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  ?count
  
  ?language ?languageLabel
  (CONCAT("/language/", SUBSTR(STR(?language), 32)) AS ?languageUrl)
   ?languageDescription 

WHERE {
  { SELECT
    (COUNT(*) AS ?count)
    ?language
  WHERE {
    [] wdt:P407 ?language   
  }
  GROUP BY ?language }

  # This is to get rid of a language number of unknown values
  FILTER EXISTS { ?language ?p [] }

#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}
ORDER BY DESC(?count)

  