{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT DISTINCT ?work ?workLabel ?workDescription {
  wd:{{ lexeme }} wdt:P1343 | ^wdt:P6254 ?work
  {{ sparql_helpers.labels(["?work"], languages) }}
  {{ sparql_helpers.descriptions(["?work"], languages) }}
}
