{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?lexeme (?lexeme_label AS ?lexemeLabel) (CONCAT("/lexeme/", SUBSTR(STR(?lexeme),32)) AS ?lexemeUrl) ?language ?languageLabel ?example_work ?example_workLabel ?example_workDescription (CONCAT("/work/", SUBSTR(STR(?example_work),32)) AS ?example_workUrl) WHERE {
  {
    SELECT (COUNT(DISTINCT ?work) AS ?count) ?lexeme (SAMPLE(?language_) AS ?language) (SAMPLE(?work) AS ?example_work) WHERE {
      {
        ?work wdt:P6254 ?lexeme .
      }
      UNION {
        ?lexeme wdt:P1343 ?work ;
                dct:language [] .
      }
      ?lexeme dct:language ?language_ .
    }
    GROUP BY ?lexeme
    ORDER BY DESC(?count)
    LIMIT 500
  }
  ?lexeme wikibase:lemma ?lexeme_label
  {{ sparql_helpers.labels(["?language", "?example_work"], languages) }}
  {{ sparql_helpers.descriptions(["?example_work"], languages) }}
}
ORDER BY DESC(?count)
