{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target1: <http://www.wikidata.org/entity/{{ q1 }}>
PREFIX target2: <http://www.wikidata.org/entity/{{ q2 }}>
# title: Nearby researchers that work with a specific topic and near a specified geographical entity
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT ?score ?author ?authorLabel (CONCAT("/author/", SUBSTR(STR(?author),32)) AS ?authorUrl) ?example_work ?example_workLabel (CONCAT("/work/", SUBSTR(STR(?example_work),32)) AS ?example_workUrl) WHERE {
  {
    SELECT ?author (SUM(?topic_score) * MAX(?inverse_distance) AS ?score) (SAMPLE(?work) AS ?example_work) WHERE {
      { # Compute distance for authors
        SELECT DISTINCT ?author (MAX(?inverse_distance_) AS ?inverse_distance) WHERE {
          { 
            SELECT DISTINCT ?organization ?geo ?other_geo ?inverse_distance_ WHERE {
              { ?organization wdt:P361*/wdt:P31/wdt:P279* wd:Q3918 .
              } UNION {
                ?organization wdt:P361*/wdt:P31/wdt:P279* wd:Q1371037 .
              } UNION {
                ?organization wdt:P361*/wdt:P31/wdt:P279* wd:Q7315155 .
              } UNION {
                ?organization wdt:P361*/wdt:P31/wdt:P279* wd:Q31855 .
              } UNION {
                ?organization wdt:P361*/wdt:P31/wdt:P279* wd:Q2385804 .
              }
              target1: wdt:P625 ?geo .
              ?organization wdt:P625 ?other_geo .
              BIND (geof:distance(?other_geo, ?geo) AS ?distance)
              FILTER(BOUND(?distance))
              BIND (1 / (?distance + 1) AS ?inverse_distance_)
            }
          }
          ?author wdt:P108 | wdt:P1416 ?organization .
        } GROUP BY ?author
      }
      {
        # A score of 3 for each authorship in the topic
        ?work wdt:P50 ?author .
        FILTER EXISTS {
          ?work wdt:P921/wdt:P279* target2: .
        }
        BIND (3 AS ?topic_score)
      }
      UNION {
        ?author wdt:P101 target2: .
        BIND (20 AS ?topic_score)
      }
    }
    GROUP BY ?author
  }
  {{ sparql_helpers.labels(["?example_work", "?author"], languages) }}
}
ORDER BY DESC(?score)
