PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT
  ?publication_date
  ?work ?workLabel
WITH{
  SELECT
    ?publication_datetime
    ?work
  WHERE {
    ?work wdt:P4510 / wdt:P279* target: ;
          wdt:P577 ?publication_datetime .
  }
  ORDER BY DESC(?publication_datetime)
  LIMIT 500
} AS %result
WHERE {
  INCLUDE %result
  BIND(xsd:date(?publication_datetime) AS ?publication_date)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . }
}
ORDER BY DESC(?publication_date)
