PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT
  (GROUP_CONCAT(?value_; separator=", ") AS ?value)
  (CONCAT("../ontology/", GROUP_CONCAT(?q; separator=",")) AS ?valueUrl)
WHERE {
  target: wdt:P2283 ?usedOntology .
  BIND(SUBSTR(STR(?usedOntology), 32) AS ?q)
  ?usedOntology rdfs:label ?value_string .
  FILTER (LANG(?value_string) = 'en')
  BIND(COALESCE(?value_string, ?q) AS ?value_)
} GROUP BY ?usedOntology
