{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?author1 ?author1Label ?author2 ?author2Label ?work ?workLabel ?pubdate WHERE {
  VALUES ?organization1 { 
   {% for q in qs %} wd:{{ q }} {% endfor %}
  }
  VALUES ?organization2 {
   {% for q in qs %} wd:{{ q }} {% endfor %}
  } 
  ?author1 ?v1 ?organization1 . 
  ?author2 ?v2 ?organization2 . 
  ?work wdt:P50 ?author1, ?author2 ;
        wdt:P577 ?pubdate .
  FILTER (?author1 <= ?author2 && ?organization1 != ?organization2)
  {{ sparql_helpers.labels(["?work", "?author1", "?author2"], languages) }}
}
ORDER BY DESC(?pubdate)
LIMIT 500
