{% import 'sparql-helpers.sparql' as sparql_helpers -%}
#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?publication_date ?citing_work ?citing_workLabel ?work ?workLabel WHERE {
  ?researcher (wdt:P108 | wdt:P463 | wdt:P1416)/wdt:P361* target: .
  ?work wdt:P50 ?researcher .
  ?citing_work wdt:P2860 ?work .
  ?citing_work wdt:P577 ?publication_datetime .
  BIND (xsd:date(?publication_datetime) AS ?publication_date)
  {{ sparql_helpers.labels(["?work", "?citing_work"], languages) }}
}
ORDER BY DESC(?publication_date)
LIMIT 200
