#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?publication_date ?citing_work (REPLACE(STR(?citing_work), ".*/", "") AS ?citing_workLabel) ?work (REPLACE(STR(?work), ".*/", "") AS ?workLabel) WHERE {
  ?researcher (wdt:P108 | wdt:P463 | wdt:P1416)/wdt:P361* target: .
  ?work wdt:P50 ?researcher .
  ?citing_work wdt:P2860 ?work .
  ?citing_work wdt:P577 ?publication_datetime .
  BIND (xsd:date(?publication_datetime) AS ?publication_date)
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . }
}
ORDER BY DESC(?publication_date)
LIMIT 200
