#defaultView:LineChart
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  ?year_of_citation
  ?number_of_citations
  ?organization ?organizationLabel  

WHERE {
  # Since 1990
  # FILTER (?year_of_citation >= "1990")
  
  # Label the results
  { # Count citations per year per organization
  SELECT
    ?year_of_citation
    (COUNT(?citing_work) AS ?number_of_citations)
    ?organization
  WHERE {
    { # Find works author by the organization
  SELECT
    DISTINCT ?work ?organization
  WHERE {
    { # Bind organizations to variable
  SELECT ?organization WHERE {
    VALUES ?organization { {% for q in qs %} wd:{{ q }} {% endfor %} }
  } }
    ?work wdt:P50 / (wdt:P108 | wdt:P463 | (wdt:P1416/wdt:P361*)) ?organization . 
  } }
    ?citing_work wdt:P2860 ?work . 
    ?citing_work wdt:P577 ?publication_date .
    BIND(STR(YEAR(?publication_date)) AS ?year_of_citation)
  }
  GROUP BY ?year_of_citation ?organization }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . }
}
ORDER BY ?year_of_citation

