{% import 'sparql-helpers.sparql' as sparql_helpers -%}
#defaultView:LineChart
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?year (COUNT(?work) AS ?number_of_works) ?organization ?organizationLabel WHERE {
  {
    SELECT DISTINCT ?year ?work ?organization WHERE {
      VALUES ?organization { {% for q in qs %} wd:{{ q }} {% endfor %} }
      ?author wdt:P108 | wdt:P463 | (wdt:P1416/wdt:P361*) ?organization .
      ?work wdt:P50 ?author .
      ?work wdt:P577 ?publication_date .
      BIND (STR(YEAR(?publication_date)) AS ?year)
    }
    GROUP BY ?work ?year ?organization
  }
  {{ sparql_helpers.labels(["?organization"], languages) }}
}
GROUP BY ?year ?organization ?organizationLabel
ORDER BY ?year
