SELECT
  (xsd:date(MAX(?publication_date_)) AS ?publication_date)
  ?work ?workLabel ?author ?authorLabel 
WHERE {
  { ?author ?p1 wd:{{ q1 }}. }
  UNION
  {
    ?author ?p2 ?something .
    ?something wdt:P361 wd:{{ q1 }}.
  }
  ?work wdt:P50 ?author;
  wdt:P921 wd:{{ q2 }}.
  OPTIONAL { ?work wdt:P577 ?publication_date_ . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
GROUP BY ?work ?workLabel ?author ?authorLabel 
ORDER BY DESC (?publication_date)
LIMIT 200
