SELECT ?part ?partLabel ?partDescription ?type
WITH {
  SELECT ?part (GROUP_CONCAT(DISTINCT ?type_label; separator=", ") AS ?type)
  WHERE {
    wd:{{ q }} wdt:P31 wd:Q4915012 ;
             wdt:P527 ?part .
    OPTIONAL { 
      ?part wdt:P31 ?type_ .
      ?type_ rdfs:label ?type_label .
      FILTER (LANG(?type_label) = 'en')
    }
  } GROUP BY ?part
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
} ORDER BY ASC(?partLabel)