{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?wpid ?organism ?organismLabel ?pathwayDescription WHERE {
  VALUES ?pathway { target: }
  OPTIONAL {
    target: wdt:P2410 ?wpid ;
            wdt:P703 ?organism .
  }
  {{ sparql_helpers.labels(["?organism"], languages) }}
  {{ sparql_helpers.descriptions(["?pathway"], languages) }}
}
