PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT DISTINCT ?guest ?guestLabel
  (CONCAT("/", SUBSTR(STR(?guest), 32)) AS ?guestUrl)
WHERE {
  BIND(target: AS ?episode)
  ?episode wdt:P5030 ?guest .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
