SELECT ?item ?itemLabel ?property_value ?property_valueLabel WHERE {
  ?item wdt:{{ p }} ?property_value .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
}
LIMIT 500