{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/prop/direct/{{ p }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?item ?itemLabel ?property_value ?property_valueLabel WHERE {
  ?item target: ?property_value .
  {{ sparql_helpers.labels(["?item", "?property_value"], languages) }}
}
LIMIT 500
