PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT ?type ?complex_or_process ?complex_or_processLabel
WITH {
  SELECT DISTINCT ?type ?complex_or_process WHERE {
    VALUES ?part { target: }
    VALUES ?process { wd:Q2996394 wd:Q4915012 }
    { ?part ^wdt:P527 ?complex_or_process . ?complex_or_process wdt:P31 wd:Q22325163 ; BIND ("complex" AS ?type ) }
    UNION
    { ?part ^wdt:P527 ?complex_or_process . ?complex_or_process wdt:P31 ?process ; BIND ("biological process" AS ?type ) }
  }
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
} ORDER BY ASC(?partLabel)
