{% import 'sparql-helpers.sparql' as sparql_helpers -%}
#defaultView:ImageGrid
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?image ?editor ?editorLabel ?venues WHERE {
  {
    SELECT DISTINCT (SAMPLE(?image_) AS ?image) ?editor (GROUP_CONCAT(?venue_label; SEPARATOR=" // ") AS ?venues) WHERE {
      # Find editors for journals published by publisher
      ?venue_ wdt:P123 target: .
      ?venue_ wdt:P98 | wdt:P5769 ?editor .
      ?editor wdt:P18 ?image_ .
      OPTIONAL {
        ?venue_ rdfs:label ?venue_label . FILTER (LANG(?venue_label) = 'en')
      }
    }
    GROUP BY ?editor
  }
  {{ sparql_helpers.labels(["?editor"], languages) }}
}
