PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
# Count the number of citations for each journal published by a specified publisher
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?number_of_citations ?work ?workLabel ?journal ?journalLabel WHERE {
  {
    SELECT ?work ?journal (COUNT(?citing_work) AS ?number_of_citations) WHERE {
      ?journal wdt:P123 target: .
      ?work wdt:P1433 ?journal .
      ?citing_work wdt:P2860 ?work
    }
    GROUP BY ?work ?journal
    ORDER BY DESC(?number_of_citations)
    LIMIT 500
  }
  # Label the result
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . } 
}
ORDER BY DESC(?number_of_citations)
