#defaultView:Timeline
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT DISTINCT ?datetime ?venue (REPLACE(STR(?venue), ".*/", "") AS ?venueLabel) WHERE {
  # Publisher
  ?venue wdt:P123 target: .
  # Periodic literature
  ?venue wdt:P31/wdt:P279* wd:Q1002697 .
  # When the journal was started 
  ?venue wdt:P571 ?datetime .
  # Label the journal
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}
ORDER BY DESC(?datetime)
LIMIT 50
