{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?author ?authorLabel (COUNT(DISTINCT ?work) AS ?count) WHERE {
  {
    ?work wdt:P31 wd:Q45182324 .
  }
  UNION {
    ?work wdt:P793 wd:Q7316896 .
  }
  UNION {
    ?work wdt:P5824 [] .
  }
  ?work wdt:P50 ?author .
  {{ sparql_helpers.labels(["?author"], languages) }}
} GROUP BY ?author ?authorLabel
  ORDER BY DESC(?count)
  LIMIT 100
