PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT DISTINCT ?entity (REPLACE(STR(?entity), ".*/", "") AS ?entityLabel) ?entityUrl ?property ?propertyLabel ?value ?valueLabel WHERE {
  {
    SELECT DISTINCT ?entity ?p ?statement ?retracted WHERE {
      BIND (target: AS ?retracted)
      ?entity ?p ?statement .
      ?statement prov:wasDerivedFrom/pr:P248 ?retracted .
    }
  }
  ?p ^wikibase:claim ?property .
  ?statement ?ps ?value .
  ?ps ^wikibase:statementProperty ?property .
  BIND (?statement AS ?entityUrl)
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
