{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT ?works ?venue ?venueLabel (CONCAT("../venue/", SUBSTR(STR(?venue),32)) AS ?venueUrl) ?venueDescription WHERE {
  {
    SELECT (COUNT(?work) AS ?works) ?venue WHERE {
      ?work wdt:P31 wd:Q45182324 ;
            wdt:P1433 ?venue .
    }
    GROUP BY ?venue
    ORDER BY DESC(?works)
    LIMIT 200
  }
  
  {{ sparql_helpers.labels(["?venue"], languages) }}
  {{ sparql_helpers.descriptions(["?venue"], languages) }}
}
ORDER BY DESC(?works)
