{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?coused ?cousedLabel ?example_work ?example_workLabel WHERE {
  # Label the result
  { # Find works that are using a specific software,
    # and find other software used in the found works
    SELECT ?coused (COUNT(?work) AS ?count) (SAMPLE(?work) AS ?example_work) WHERE {
      ?work wdt:P4510/wdt:P279* target: ;
            wdt:P4510 ?coused .
      FILTER (?coused != target:)
    }
    GROUP BY ?coused
  }
  {{ sparql_helpers.labels(["?coused", "?example_work"], languages) }}
}
ORDER BY DESC(?count)
