{% macro labels(variables, languages) -%}
  {% for variable in variables -%}
    {% for language in languages -%}
      OPTIONAL { {{ variable }} <http://www.w3.org/2000/01/rdf-schema#label> {{ variable }}Label. FILTER(LANG({{ variable }}Label) = "{{ language }}") }
    {% endfor -%}
    {%- if not loop.last %}
    {% endif %}
  {%- endfor %}
{%- endmacro -%}

{% macro labels_unbound(variables, languages) -%}
  {% for variable in variables -%}
    BIND (IF(BOUND ({{ variable }}), {{ variable }}, <http://doesntexist.example.com/nexistepas>) AS {{ variable }}_)
    {% for language in languages -%}
      OPTIONAL { {{ variable }}_ <http://www.w3.org/2000/01/rdf-schema#label> {{ variable }}Label. FILTER(LANG({{ variable }}Label) = "{{ language }}") }
    {% endfor -%}
    {%- if not loop.last %}
    {% endif %}
  {%- endfor %}
{%- endmacro -%}

{% macro descriptions(variables, languages) -%}
  {% for variable in variables -%}
    {% for language in languages -%}
      OPTIONAL { {{ variable }} <http://schema.org/description> {{ variable }}Description. FILTER(LANG({{ variable }}Description) = "{{ language }}") }
    {% endfor -%}
    {%- if not loop.last %}
    {% endif %}
  {%- endfor %}
{%- endmacro -%}

{% macro descriptions_unbound(variables, languages) -%}
  {% for variable in variables -%}
    BIND (IF(BOUND ({{ variable }}), {{ variable }}, <http://doesntexist.example.com/nexistepas>) AS {{ variable }}_)
    {% for language in languages -%}
      OPTIONAL { {{ variable }}_ <http://schema.org/description> {{ variable }}Description. FILTER(LANG({{ variable }}Description) = "{{ language }}") }
    {% endfor -%}
    {%- if not loop.last %}
    {% endif %}
  {%- endfor %}
{%- endmacro -%}
