# title: Scatterplot of project budgets associated with a funder
#defaultView:ScatterChart
SELECT ?start_time ?budget ?project ?projectLabel WHERE {
  ?project wdt:P859+ wd:{{ q }} .
  ?project wdt:P2769 ?budget .
  ?project (wdt:P580 | wdt:P571) ?start_time .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,da,es,fr,jp,nl,no,ru,sv,zh". }
}