{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
# title: Co-funders to a specific funder including an example funded work
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?sponsor ?sponsorLabel (CONCAT("/sponsor/", SUBSTR(STR(?sponsor),32)) AS ?sponsorUrl) ?example_work ?example_workLabel (CONCAT("/work/", SUBSTR(STR(?example_work),32)) AS ?example_workUrl) WHERE {
  # Label the result
  {
    SELECT (COUNT(?work) AS ?count) ?sponsor (SAMPLE(?work) AS ?example_work) WHERE {
      ?work wdt:P859+ target: .
      ?work wdt:P859+ ?sponsor .
      FILTER (target: != ?sponsor)
    }
    GROUP BY ?sponsor
  }
  {{ sparql_helpers.labels(["?sponsor", "?example_work"], languages) }}
}
ORDER BY DESC(?count)
