SELECT ?publication_date ?number_of_citations ?work ?workLabel ?quote
WITH {
  SELECT (MIN(?date) AS ?publication_date) (COUNT(?citing_work) as ?number_of_citations) ?work (SAMPLE(?quote_) AS ?quote)
  WHERE {
    ?work p:P859+ ?sponsor_statement .
    ?sponsor_statement ps:P859+ wd:{{ q }} .
    OPTIONAL { ?sponsor_statement prov:wasDerivedFrom/pr:P1683 ?quote_ . }
    OPTIONAL {
      ?work wdt:P577 ?datetime .
      BIND(xsd:date(?datetime) AS ?date)
    }
    OPTIONAL { ?citing_work wdt:P2860 ?work }
  } 
  GROUP BY ?work
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
} 
ORDER BY DESC(?publication_date) DESC(?number_of_citations)
LIMIT 1000
