#defaultView:BubbleChart
SELECT
  ?count ?topic ?topicLabel
WITH {
  SELECT (COUNT(?work) AS ?count) ?topic
  WHERE {
    ?work wdt:P859+ wd:{{ q }} .
    ?work wdt:P921 ?topic .
  } 
  GROUP BY ?topic
  ORDER BY DESC(?count)
  LIMIT 200
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,nl,no,ru,sv,zh" }
} 
ORDER BY DESC(?count)
