{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#defaultView:Graph
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT (?child_ AS ?child) ?childLabel ?rgb (?parent_ AS ?parent) ?parentLabel WHERE {
  {
    # Parent taxa
    target: wdt:P171* ?child_ .
    ?child_ wdt:P171 ?parent_ .
    BIND ("FFFFFF" AS ?rgb)
  } UNION {
    # Child taxa
    {SELECT ?child_ ?parent_ WHERE {
      BIND (target: AS ?parent_) .
      ?child_ wdt:P171 ?parent_ .
    } LIMIT 100}
    BIND ("DDDDDD" AS ?rgb)
  } UNION {
    BIND (target: AS ?child_) .
    ?child_ wdt:P171 ?parent_ .
    BIND ("FF0000" AS ?rgb)
  }

  OPTIONAL {
    ?child_ wdt:P105 ?child_rank_ .
    {{ sparql_helpers.labels(["?child_rank_"], languages) }}
  }
  OPTIONAL {
    ?parent_ wdt:P105 ?parent_rank_ .
    {{ sparql_helpers.labels(["?parent_rank_"], languages) }}
  }
  {{ sparql_helpers.labels(["?child_", "?parent_"], languages) }}

  BIND (CONCAT(?child_Label, " - ", COALESCE(?child_rank_Label, "???")) AS ?childLabel)
  BIND (CONCAT(?parent_Label, " - ", COALESCE(?parent_rank_Label, "???")) AS ?parentLabel)
}
