{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#title: Taxa that co-occur with the target taxon in the literature
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count (CONCAT("/topics/", SUBSTR(STR(target:),32), ",", SUBSTR(STR(?taxon),32)) AS ?countUrl) ?taxon ?taxonLabel (CONCAT("/taxon/", SUBSTR(STR(?taxon),32)) AS ?taxonUrl) ?example_work ?example_workLabel (CONCAT("/work/", SUBSTR(STR(?example_work),32)) AS ?example_workUrl) WHERE {
  # Label the results
  {
    SELECT (COUNT(?work) AS ?count) ?taxon (SAMPLE(?work) AS ?example_work) WHERE {
      # Find works for the specific queried topic
      ?work wdt:P921 target: .
      # Find co-occuring topics
      ?work wdt:P921 ?taxon .
      # Filter for taxa
      ?taxon wdt:P105 ?taxonrank .
      # Avoid listing the queried topic itself
      FILTER (target: != ?taxon)
    }
    GROUP BY ?taxon
  }
  {{ sparql_helpers.labels(["?taxon", "?example_work"], languages) }}
}
ORDER BY DESC(?count)
LIMIT 200
