{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#defaultView:Graph
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT (?_child AS ?child) ?childLabel ?rgb (?_parent AS ?parent) ?parentLabel WHERE {
  {
    # Parent taxa
    target: wdt:P171+ ?_child .
    ?_child wdt:P171 ?_parent .
    BIND ("FFFFFF" AS ?rgb)
  } UNION {
    # Child taxa
    {SELECT ?_child ?_parent WHERE {
      BIND (target: AS ?_parent) .
      ?_child wdt:P171 ?_parent .
    } LIMIT 100}
    BIND ("DDDDDD" AS ?rgb)
  } UNION {
    BIND (target: AS ?_child) .
    ?_child wdt:P171 ?_parent .
    BIND ("FF0000" AS ?rgb)
  }

  OPTIONAL {
    ?_child wdt:P105 ?_childRank .
    {{ sparql_helpers.labels(["?_childRank"], languages) }}
  }
  OPTIONAL {
    ?_parent wdt:P105 ?_parentRank .
    {{ sparql_helpers.labels(["?_parentRank"], languages) }}
  }
  {{ sparql_helpers.labels(["?_child", "?_parent"], languages) }}

  BIND (CONCAT(?_childLabel, " - ", COALESCE(?_childRankLabel, "???")) AS ?childLabel)
  BIND (CONCAT(?_parentLabel, " - ", COALESCE(?_parentRankLabel, "???")) AS ?parentLabel)
}
