{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?protein ?proteinLabel ?proteinDescription ?gene ?geneLabel {
  ?protein wdt:P31 wd:Q8054 ;
           wdt:P703 target: ;
           wdt:P702 ?gene.
  {{ sparql_helpers.labels(["?protein", "?gene"], languages) }}
  {{ sparql_helpers.descriptions(["?protein"], languages) }}
}
