# title: List of topics
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  ?topic ?topicLabel ?topicDescription (CONCAT("/topic/", SUBSTR(STR(?topic), 32)) AS ?topicUrl)
  ?example_work ?example_workLabel (CONCAT("/work/", SUBSTR(STR(?example_work), 32)) AS ?example_workUrl)

WHERE {
  { SELECT ?topic (SAMPLE(?work) AS ?example_work) WHERE {
    VALUES ?topic { {% for q in qs %} wd:{{ q }} {% endfor %} }
    OPTIONAL { 
      ?work wdt:P921 ?topic ; wdt:P31 wd:Q13442814 .
    }
  }
  GROUP BY ?topic }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . }
}
