{% import 'sparql-helpers.sparql' as sparql_helpers -%}

# title: List of works on any combination of specific topics
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?count (MIN(?publication_date_) AS ?publication_date) ?work ?workLabel (CONCAT("/work/", SUBSTR(STR(?work),32)) AS ?workUrl) ?topics ?topicsUrl WHERE {
  {
    SELECT (COUNT(DISTINCT ?mainTopic) AS ?count) ?work (GROUP_CONCAT(DISTINCT ?topicLabel; SEPARATOR=" // ") AS ?topics) (CONCAT("../topics/", GROUP_CONCAT(DISTINCT SUBSTR(STR(?topic), 32); SEPARATOR=",")) AS ?topicsUrl) WHERE {
      {
        SELECT DISTINCT ?topic ?mainTopic WHERE {
          {% for q in qs -%}
          { ?topic wdt:P31?/wdt:P279* wd:{{ q }} . BIND(wd:{{ q }} as ?mainTopic) }
          UNION
          { ?topic wdt:P361+ wd:{{ q }} . BIND(wd:{{ q }} as ?mainTopic) }
          UNION
          { ?topic wdt:P1269+ wd:{{ q }} . BIND(wd:{{ q }} as ?mainTopic) }{% if not loop.last %}
          UNION{% endif %}
          {% endfor %}
        }
      }

      ?work wdt:P921 ?topic .
      {{ sparql_helpers.labels(["?topic"], languages) }}
    }
    GROUP BY ?work
    HAVING (?count > 1)
    ORDER BY DESC(?count)
    LIMIT 200
  }
  OPTIONAL {
    ?work wdt:P577 ?publication_datetime .
    BIND (xsd:date(?publication_datetime) AS ?publication_date_)
  }

  {{ sparql_helpers.labels(["?work"], languages) }}
}
GROUP BY ?count ?work ?workLabel ?topics ?topicsUrl
ORDER BY DESC(?count) DESC(?publication_date)
