{% import 'sparql-helpers.sparql' as sparql_helpers -%}

# tool: scholia
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?couses ?citing_works ?work ?workLabel (CONCAT("/work/", SUBSTR(STR(?work), 32)) AS ?workUrl) WHERE {
  { # Count citations
    SELECT (COUNT(DISTINCT ?citing_work) AS ?citing_works) ?work (COUNT(DISTINCT ?use) AS ?couses) WHERE {
      ?work wdt:P4510 target: .
      OPTIONAL {
        ?work wdt:P4510 ?use . FILTER (?use != target:)
      }
      OPTIONAL {
        ?citing_work wdt:P2860 ?work .
      }
    }
    GROUP BY ?work
    # Disabled to also show works with few co-uses
    # HAVING (?couses < 1)
    ORDER BY DESC(?count)
    LIMIT 100
  }

  # Label results
  {{ sparql_helpers.labels(["?work"], languages) }}
}
ORDER BY ?couses DESC(?citing_works)
