{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#defaultView:BarChart
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?year (COUNT(?work) AS ?number_of_works) ?useLabel WHERE {
  {
    SELECT (MIN(?year_) AS ?year) ?work ?use WHERE {
      ?use wdt:P279* target: .
      ?work wdt:P4510 ?use ;
            wdt:P577 ?publication_datetime .
      BIND (STR(YEAR(?publication_datetime)) AS ?year_)
    }
    GROUP BY ?work ?use
  }
  {{ sparql_helpers.labels(["?use"], languages) }}
}
GROUP BY ?year ?useLabel
ORDER BY ?year
