{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#defaultView:BubbleChart
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?topic ?topicLabel WHERE {
  {
    SELECT (COUNT(?work) AS ?count) ?topic WHERE {
      ?work wdt:P4510/wdt:P279* target: ;
            wdt:P921 ?topic .
    }
    GROUP BY ?topic
    ORDER BY DESC(?count)
    LIMIT 200
  }
  {{ sparql_helpers.labels(["?topic"], languages) }}
}
ORDER BY DESC(?count)
