{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?publication_date ?work ?workLabel (CONCAT("/work/", SUBSTR(STR(?work), 32)) AS ?workUrl) WHERE {
  {
    SELECT ?publication_datetime ?work WHERE {
      ?work wdt:P4510/wdt:P279* target: ;
            wdt:P577 ?publication_datetime .
    }
    ORDER BY DESC(?publication_datetime)
    LIMIT 1000
  }
  BIND (xsd:date(?publication_datetime) AS ?publication_date)
  {{ sparql_helpers.labels(["?work"], languages) }}
}
ORDER BY DESC(?publication_date)
