#defaultView:BubbleChart

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

SELECT
  ?count
  ?topic ?topicLabel
WITH{
  SELECT
    (COUNT(?work) AS ?count)
    ?topic
  WHERE {
    ?work wdt:P4510 / wdt:P279* target: ; 
          wdt:P921 ?topic .
  }
  GROUP BY ?topic
  ORDER BY DESC(?count)
  LIMIT 200
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . }
}
ORDER BY DESC(?count)

