# title: Citation distribution for a venue

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

#defaultView:LineChart
SELECT
  ?number_of_citations (COUNT(?work) AS ?count)
WHERE {
  {
    SELECT ?work (COUNT(?citing_work) AS ?number_of_citations)
    WHERE {
      ?work wdt:P1433 target: .
      OPTIONAL { ?citing_work wdt:P2860 ?work . }
    }
    GROUP BY ?work 
  }
} 
GROUP BY ?number_of_citations
ORDER BY DESC(?number_of_citations)
