#defaultView:AreaChart

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  ?year
  ?works
  ?topic ?topicLabel

WHERE {
  { SELECT
    ?year 
    (COUNT(?work) AS ?works)
    ?topic
  WHERE {
    { SELECT 
    ?work
  WHERE {
    ?work wdt:P1433 target: .
  } }
    { SELECT
    (COUNT(?work) AS ?count)
    ?topic
  WHERE {
    { SELECT 
    ?work
  WHERE {
    ?work wdt:P1433 target: .
  } }
    ?work wdt:P921 ?topic .
  }
  GROUP BY ?topic
  ORDER BY DESC(?count)
  LIMIT 5 }
    ?work wdt:P921 ?topic ;
          wdt:P577 ?publication_datetime .
    BIND(STR(YEAR(?publication_datetime)) AS ?year)
  }
  GROUP BY ?year ?topic }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}
ORDER BY ?year