# title: Prolific authors for a specific journal
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?author (REPLACE(STR(?author), ".*/", "") AS ?authorLabel) ?orcid ?example_work (REPLACE(STR(?example_work), ".*/", "") AS ?example_workLabel) WHERE {
  { # Count the number of works author by the author publishing in the journal
    SELECT ?author (COUNT(?work) AS ?count) (SAMPLE(?work) AS ?example_work) WHERE {
      ?work wdt:P50 ?author ;
            wdt:P1433 target: .
    }
    GROUP BY ?author
  }
  # Include optional ORCID iD
  OPTIONAL {
    ?author wdt:P496 ?orcid .
  }
  # SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" . } 
}
ORDER BY DESC(?count)
LIMIT 50
