{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#title: Recent works published in venue
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?publication_date ?work ?workLabel (GROUP_CONCAT(DISTINCT ?authorLabel; SEPARATOR=", ") AS ?authors) (CONCAT("../authors/", GROUP_CONCAT(DISTINCT SUBSTR(STR(?author),32); SEPARATOR=",")) AS ?authorsUrl) WHERE {
  {
    SELECT DISTINCT ?work (MIN(?publication_date_) AS ?publication_date) WHERE {
      ?work wdt:P1433 target: .
      OPTIONAL {
        ?work wdt:P577 ?publication_datetime .
        BIND (xsd:date(?publication_datetime) AS ?publication_date_)
      }
    }
    GROUP BY ?work
    ORDER BY DESC(?publication_date)
    LIMIT 1000
  }
  OPTIONAL {
    ?work wdt:P50 ?author .
    {{ sparql_helpers.labels(["?author"], languages) }}
  }
  {{ sparql_helpers.labels(["?work"], languages) }}
}
GROUP BY ?publication_date ?work ?workLabel
ORDER BY DESC(?publication_date)
