{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
# title: Author gender distribution for a specific venue
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT (COUNT(DISTINCT ?author) AS ?count) ?gender ?genderLabel WHERE {
  ?work wdt:P1433 target: .
  ?work wdt:P50 ?author .
  ?author wdt:P21 ?gender .
  {{ sparql_helpers.labels(["?gender"], languages) }}
}
GROUP BY ?gender ?genderLabel
ORDER BY DESC(?count)
