{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX target1: <http://www.wikidata.org/entity/{{ q1 }}>
PREFIX target2: <http://www.wikidata.org/entity/{{ q2 }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?publication_date ?work ?workLabel (CONCAT("/work/", SUBSTR(STR(?work),32)) AS ?workUrl) WHERE {
  ?work wdt:P1433 target1: ;
        wdt:P4510 target2: .
  OPTIONAL {
    ?work wdt:P577 ?publication_datetime .
    BIND (xsd:date(?publication_datetime) AS ?publication_date)
  }
  {{ sparql_helpers.labels(["?work"], languages) }}
}
ORDER BY DESC(?publication_date)
