{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?count ?work ?workLabel (CONCAT("/work/", SUBSTR(STR(?work),32)) AS ?workUrl) ?topics WHERE {
  { # Count citations
    SELECT (COUNT(?citing_work) AS ?count) ?work (COUNT(DISTINCT ?topic) AS ?topics) WHERE {
      ?work wdt:P1433 target: .
      OPTIONAL {
        ?work wdt:P921 ?topic
      }
      OPTIONAL {
        ?citing_work wdt:P2860 ?work .
      }
    }
    GROUP BY ?work
    ORDER BY DESC(?count)
    LIMIT 1000
  }
  FILTER (?topics < 2)

  # Label results
  {{ sparql_helpers.labels(["?work"], languages) }}
}
ORDER BY DESC(?count) ?topics
