PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT ?type (REPLACE(STR(?type), ".*/", "") AS ?typeLabel) ?count 
WHERE {
  { SELECT DISTINCT ?type (COUNT(?item) AS ?count) WHERE {
    ?item wdt:P5008 wd:{{ q }};
            (wdt:P31|wdt:P279) ?type.
    }
    GROUP BY ?type ?count
    ORDER BY DESC (?count) }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en,da,de,es,fr,it,sv,uk,zh". }
}
ORDER BY DESC (?count)