{% import 'sparql-helpers.sparql' as sparql_helpers -%}
#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?count ?author ?authorLabel ?authorDescription (CONCAT("/author/", SUBSTR(STR(?author),32)) AS ?authorUrl) (COALESCE(?orcid_, CONCAT("orcid-search/search/?searchQuery=", ?authorLabel)) AS ?orcid) WHERE {
  {
    SELECT ?author (COUNT(?work) AS ?count) WHERE {
      {
        ?work wdt:P6104 target: .
      }
      UNION {
        ?work wdt:P5008 target: .
      }
      ?work wdt:P50 ?author .
    }
    GROUP BY ?author
    ORDER BY DESC(?count)
    LIMIT 200
  }
  # Include optional ORCID iD
  OPTIONAL {
    ?author wdt:P496 ?orcid_ .
  }
  {{ sparql_helpers.labels(["?author"], languages) }}
  {{ sparql_helpers.descriptions(["?author"], languages) }}
}
ORDER BY DESC(?count)
