{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?count ?wikiproject ?wikiprojectLabel (CONCAT("/wikiproject/", SUBSTR(STR(?wikiproject),32)) AS ?wikiprojectUrl) ?example_entity ?example_entityLabel (CONCAT("/", SUBSTR(STR(?example_entity),32)) AS ?example_entityUrl) WHERE {
  # Label the results
  {
    SELECT (COUNT(?work) AS ?count) ?wikiproject (SAMPLE(?work) AS ?example_entity) WHERE {
      # Find works for the specific queried wikiproject
      VALUES ?p { wdt:P6104 wdt:P5008 }
      ?work ?p target: .

      # Find co-occuring wikiprojects
      ?work ?p ?wikiproject .
      # Avoid listing the queried wikiproject
      FILTER (target: != ?wikiproject)
    }
    GROUP BY ?wikiproject
  }
  {{ sparql_helpers.labels(["?wikiproject", "?example_entity"], languages) }}

}
ORDER BY DESC(?count)
