{% import 'sparql-helpers.sparql' as sparql_helpers -%}
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?type ?typeLabel ?count WHERE {
  {
    SELECT DISTINCT ?type (COUNT(?item) AS ?count) WHERE {
      ?item wdt:P5008 target: .
      ?item wdt:P31|wdt:P279 ?type .
    }
    GROUP BY ?type ?count
    ORDER BY DESC(?count)
  }
  {{ sparql_helpers.labels(["?type"], languages) }}
}
ORDER BY DESC(?count)
