PREFIX target: <http://www.wikidata.org/entity/{{ q }}>

PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT ?intention (REPLACE(STR(?intention), ".*/", "") AS ?intentionLabel) (CONCAT("/cito/", SUBSTR(STR(?intention), 32)) AS ?intentionUrl)  
?count ?example_work_for_intention ?example_work_for_intentionLabel 

WHERE {
  { SELECT ?intention (COUNT(DISTINCT ?citingArticle) AS ?count) (SAMPLE(?citingArticle) AS ?example_work_for_intention) {
    VALUES ?CITEDARTICLE { target: }
    ?citingArticle p:P2860 ?citationStatement .
    ?citationStatement pq:P3712 ?intention ;
                       ps:P2860 ?CITEDARTICLE .
    ?intention wdt:P31 wd:Q96471816 .
  }
  GROUP BY ?intention }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}
GROUP BY ?intention ?intentionLabel ?count ?example_work_for_intention ?example_work_for_intentionLabel
ORDER BY DESC(?count)
