{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?work ?workLabel ?example_author ?example_authorLabel WHERE {
  {
    VALUES ?work { {% for q in qs -%} wd:{{ q }} {% endfor -%} }
    FILTER NOT EXISTS { ?work wdt:P50 [] }
  }
  UNION {
    {
      SELECT ?work (SAMPLE(?author) AS ?example_author) WHERE {
        VALUES ?work { {% for q in qs -%} wd:{{ q }} {% endfor -%} }
        ?work wdt:P50 ?author
      }
      GROUP BY ?work
    }
    {{ sparql_helpers.labels(["?work", "?example_author"], languages) }}
  }
}
