{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#title: Statements referencing the {{ q }} article
#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel ?unit ?unitLabel WHERE {
  {
    { SELECT ?statement WHERE { ?statement prov:wasDerivedFrom/pr:P248 target: . } }
    ?item a wikibase:Item ; ?p ?statement .
    ?property wikibase:claim ?p ; wikibase:statementProperty ?ps .
    ?statement ?ps ?value .
    FILTER NOT EXISTS {
      ?property wikibase:statementValueNormalized ?pn .
      FILTER (ISLITERAL(?value))
    }
  } UNION {
    { SELECT ?statement WHERE { ?statement prov:wasDerivedFrom/pr:P248 target: . } }
    ?item a wikibase:Item ; ?p ?statement .
    ?property wikibase:claim ?p ; wikibase:statementValueNormalized ?pn .
    ?statement ?pn ?value .
    FILTER (ISLITERAL(?value))
  }

  OPTIONAL {
    { SELECT ?statement WHERE { ?statement prov:wasDerivedFrom/pr:P248 target: . } }
    ?item a wikibase:Item ; ?p ?statement .
    ?property wikibase:claim ?p ; wikibase:statementProperty ?ps ; wikibase:statementValue ?psv .
    ?statement ?psv [ wikibase:quantityUnit ?unit ]
    {{ sparql_helpers.labels(["?unit"], languages) }}
  }

  {{ sparql_helpers.labels(["?item", "?property", "?value"], languages) }}
}
ORDER BY ?item ?property
LIMIT 2000
