{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?intention ?intentionLabel (CONCAT("/cito/", SUBSTR(STR(?intention),32)) AS ?intentionUrl) ?count ?example_work_for_intention ?example_work_for_intentionLabel WHERE {
  {
    SELECT ?intention (COUNT(DISTINCT ?citingArticle) AS ?count) (SAMPLE(?citingArticle) AS ?example_work_for_intention) {
      ?citingArticle p:P2860 ?citationStatement .
      ?citationStatement pq:P3712 ?intention ;
                         ps:P2860 target: .
      ?intention wdt:P31 wd:Q96471816 .
    }
    GROUP BY ?intention
  }
  {{ sparql_helpers.labels(["?intention", "?example_work_for_intention"], languages) }}
}
ORDER BY DESC(?count)
