{% import 'sparql-helpers.sparql' as sparql_helpers -%}

PREFIX target1: <http://www.wikidata.org/prop/{{ q }}>
PREFIX target2: <http://www.wikidata.org/prop/{{ q2 }}>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?citingArticle ?citingArticleLabel ?intention ?intentionLabel (CONCAT("/cito/", SUBSTR(STR(?intention),32)) AS ?intentionUrl) WHERE {
  ?citingArticle p:P2860 ?citationStatement .
  ?citationStatement pq:P3712 target2: ;
                     ps:P2860 target1: .
  {{ sparql_helpers.labels(["?citingArticle", "?intention"], languages) }}
}
