{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#title: List of authors with works that are cited by the specified work
#defaultView:Table
PREFIX target: <http://www.wikidata.org/entity/{{ q }}>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?cited_works ?author ?authorLabel ?authorDescription (CONCAT("/author/", SUBSTR(STR(?author),32)) AS ?authorUrl) ?cited_work_example ?cited_work_exampleLabel (CONCAT("/work/", SUBSTR(STR(?cited_work_example),32)) AS ?cited_work_exampleUrl) WHERE {
  {
    SELECT (COUNT(?cited_work) AS ?cited_works) ?author (SAMPLE(?cited_work) AS ?cited_work_example) WHERE {
      # Find works that are cited by the queried work
      target: wdt:P2860 ?cited_work .
      ?cited_work wdt:P50 ?author .
    }
    GROUP BY ?author
    # Limit the number of results to avoid downloading too much data
    ORDER BY DESC(?cited_works)
    LIMIT 1000
  }
  # Label the result
  {{ sparql_helpers.labels(["?author", "?cited_work_example"], languages) }}
  {{ sparql_helpers.descriptions(["?author"], languages) }}
}
ORDER BY DESC(?cited_works)
