SELECT
  ?title ?titleUrl
  ?wikipedia ?wikipediaLabel
  ?item ?itemLabel ?itemDescription 
WHERE {
  {
    SELECT ?title_ ?titleUrl ?item ?wikipedia {
      SERVICE wikibase:mwapi {
        bd:serviceParam wikibase:endpoint "da.wikipedia.org" ;
                        wikibase:api "Generator" ;
			mwapi:generator "search" ;
                        mwapi:gsrsearch '{{ q }}{% for doi in dois %} OR "{{ doi }}"{% endfor %}' ;
                        mwapi:gsrlimit "200" .
        ?title_ wikibase:apiOutput mwapi:title .
	?item wikibase:apiOutputItem mwapi:item .
      }
      BIND(URI(CONCAT("https://da.wikipedia.org/wiki/", ENCODE_FOR_URI(REPLACE(?title_, " ", "_")))) AS ?titleUrl)
      BIND(wd:Q181163 AS ?wikipedia)
    } 
  }
  UNION
  {
    SELECT ?title_ ?titleUrl ?item ?wikipedia {
      SERVICE wikibase:mwapi {
        bd:serviceParam wikibase:endpoint "de.wikipedia.org" ;
                        wikibase:api "Generator" ;
			mwapi:generator "search" ;
                        mwapi:gsrsearch '{{ q }}{% for doi in dois %} OR "{{ doi }}"{% endfor %}' ;
                        mwapi:gsrlimit "200" .
        ?title_ wikibase:apiOutput mwapi:title .
	?item wikibase:apiOutputItem mwapi:item .
      }
      BIND(URI(CONCAT("https://de.wikipedia.org/wiki/", ENCODE_FOR_URI(REPLACE(?title_, " ", "_")))) AS ?titleUrl)
      BIND(wd:Q48183 AS ?wikipedia)
    }     
  }
  UNION
  {
    SELECT ?title_ ?titleUrl ?item ?wikipedia {
      SERVICE wikibase:mwapi {
        bd:serviceParam wikibase:endpoint "en.wikipedia.org" ;
                        wikibase:api "Generator" ;
			mwapi:generator "search" ;
                        mwapi:gsrsearch '{{ q }}{% for doi in dois %} OR "{{ doi }}"{% endfor %}' ;
                        mwapi:gsrlimit "200" .
        ?title_ wikibase:apiOutput mwapi:title .
	?item wikibase:apiOutputItem mwapi:item .
      }
      BIND(URI(CONCAT("https://en.wikipedia.org/wiki/", ENCODE_FOR_URI(REPLACE(?title_, " ", "_")))) AS ?titleUrl)
      BIND(wd:Q328 AS ?wikipedia)
    }     
  }
  UNION
  {
    SELECT ?title_ ?titleUrl ?item ?wikipedia {
      SERVICE wikibase:mwapi {
        bd:serviceParam wikibase:endpoint "fr.wikipedia.org" ;
                        wikibase:api "Generator" ;
			mwapi:generator "search" ;
                        mwapi:gsrsearch '{{ q }}{% for doi in dois %} OR "{{ doi }}"{% endfor %}' ;
                        mwapi:gsrlimit "200" .
        ?title_ wikibase:apiOutput mwapi:title .
	?item wikibase:apiOutputItem mwapi:item .
      }
      BIND(URI(CONCAT("https://fr.wikipedia.org/wiki/", ENCODE_FOR_URI(REPLACE(?title_, " ", "_")))) AS ?titleUrl)
      BIND(wd:Q8447 AS ?wikipedia)
    }     
  }
  hint:Prior hint:runFirst "true" .
  BIND(CONCAT(?title_, "&nbsp;↗") AS ?title)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
} 