{% import 'sparql-helpers.sparql' as sparql_helpers -%}

#defaultView:LineChart
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?year (COUNT(DISTINCT ?citing_work) AS ?number_of_citations) (CONCAT(?work1Label, " (", SUBSTR(STR(?work1), 32), ")") AS ?work) WHERE {
  VALUES ?work1 { {% for q in qs -%} wd:{{ q }} {% endfor -%} }
  ?citing_work wdt:P2860 ?work1 .
  # Year of citation
  ?citing_work wdt:P577 ?date .
  BIND (STR(YEAR(?date)) AS ?year)
  {{ sparql_helpers.labels(["?work1"], languages) }}
}
GROUP BY ?year ?work1 ?work1Label
